---
- name: Check installed Python packages
  hosts: localhost
  tasks:
    - name: Install pynetbox
      pip:
        name: pynetbox
        state: present
    
    - name: List installed Python packages
      command: pip list
      register: pip_list
    - debug:
        var: pip_list.stdout_lines

