---
plugin: netbox.netbox.nb_inventory
validate_certs: False
group_by:
 - device_roles
 - sites

 # vars:
    #netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
    #netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"
