---
- name: Lookup NetBox Device Data Based on Role
  hosts: localhost
  gather_facts: no
  vars:
    netbox_url: "https://mnqh6527.cloud.netboxapp.com/"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"
    github_repo: "https://github.com/ayoemman/NetboxProj.git"
    github_token: "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"
    config_file_path: "/tmp/config_file.txt"

  tasks:
    - name: Get device configurations from NetBox
      uri:
        url: "{{ netbox_url }}dcim/devices/"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
        return_content: yes
      register: netbox_response

    - name: Write configuration to local file
      copy:
        content: "{{ netbox_response.content }}"
        dest: "{{ config_file_path }}"

    - name: Clone GitHub repository
      git:
        repo: "{{ github_repo }}"
        dest: "/tmp/repo"
        version: main
        force: yes
      register: git_result

    - name: Copy configuration file to repository
      copy:
        src: "{{ config_file_path }}"
        dest: "/tmp/repo/config_file.txt"
    
    - name: Set Git user name
      command: git config --global user.name "ayoemman"
      args:
        chdir: "/tmp/repo"

    - name: Set Git user email
      command: git config --global user.email "ayoemman006@gmail.com"
      args:
        chdir: "/tmp/repo"

    - name: Commit changes to repository
      command: git commit -am "Add configuration file"
      args:
        chdir: "/tmp/repo"

    - name: Push changes to GitHub
      command: git push origin master
      args:
        chdir: "/tmp/repo"
      environment:
        GIT_TOKEN: "{{ github_token }}"
