---
- name: Playbook to interact with NetBox
  hosts: aap
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: Install pynetbox if not already installed
      pip:
        name: pynetbox
        state: present
        
    # query a list of devices
    - name: Obtain list of devices from NetBox
      debug:
        msg: >
          "Device {{ item.value.display_name }} (ID: {{ item.key }}) was
          manufactured by {{ item.value.device_type.manufacturer.name }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
                      api_endpoint='https://mnqh6527.cloud.netboxapp.com/',
                      token='7e1c591e544353bedaeba2fdca5309ff16dfe268') }}"

      # This example uses an API Filter
    - name: Obtain list of devices from NetBox
      debug:
        msg: >
          "Device {{ item.value.display_name }} (ID: {{ item.key }}) was
          manufactured by {{ item.value.device_type.manufacturer.name }}"
      loop: "{{ query('netbox.netbox.nb_lookup', 'devices',
                      api_endpoint='https://mnqh6527.cloud.netboxapp.com/',
                      api_filter='role=management tag=Dell'),
                      token='7e1c591e544353bedaeba2fdca5309ff16dfe268') }}"
