---
- name: Obtain list of devices from NetBox
  hosts: localhost
  gather_facts: no
  collections:
    - netbox.netbox

  vars:
    netbox_url: "https://mnqh6527.cloud.netboxapp.com/"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"

  tasks:
    - name: Retrieve list of devices from NetBox
      netbox.netbox.netbox_device:
        api_url: "{{ netbox_url }}"
        api_token: "{{ netbox_token }}"
        state: query
      register: devices

    - name: Display devices
      debug:
        msg: "{{ devices }}"
