---
- name: Playbook to interact with NetBox
  hosts: localhost
  gather_facts: no
  collections:
    - netbox.netbox
  tasks:
    - name: Create aggregate within NetBox with only required information
      netbox.netbox.netbox_aggregate:
        netbox_url: https://mnqh6527.cloud.netboxapp.com/
        netbox_token: 7e1c591e544353bedaeba2fdca5309ff16dfe268
        data:
          prefix: http://10.0.0.10/26
          rir: Test RIR
        state: present
