---
- name: Playbook to interact with NetBox
  hosts: aap
  gather_facts: no

  tasks:
  - name: Get device configurations from NetBox
    uri:
      url: "{{ netbox_url }}dcim/devices/"
      method: GET
      headers:
        Authorization: "Token {{ netbox_token }}"
      return_content: yes
    register: netbox_response
