---
- name: Retrieve device details from NetBox
  hosts: localhost
  gather_facts: no
  collections:
    - netbox.netbox

  vars:
    netbox_url: "https://mnqh6527.cloud.netboxapp.com/"
    netbox_token: "7e1c591e544353bedaeba2fdca5309ff16dfe268"

  tasks:
    - name: Retrieve a device by name
      netbox.netbox.netbox_device:
        api_url: "{{ netbox_url }}"
        api_token: "{{ netbox_token }}"
        name: "NLAMS01-SW-1"  # Replace with the actual device name
      register: device_info

    - name: Display device information
      debug:
        msg: "{{ device_info }}"
